[target.armv7-unknown-linux-gnueabihf]
volumes = [
    { host = "/home/mixailo/openssl-armhf", guest = "/openssl-armhf" }
]
env = {    "OPENSSL_DIR" = "/openssl-armhf",    "OPENSSL_LIB_DIR" = "/openssl-armhf/lib",    "OPENSSL_INCLUDE_DIR" = "/openssl-armhf/include",    "PKG_CONFIG_PATH" = "/openssl-armhf/lib/pkgconfig",    "PKG_CONFIG_ALLOW_CROSS" = "1" }